/* eslint-disable max-len -- generated LQIP data URLs */
/**
 * Auto-generated by scripts/generate-persona-image-assets.mjs
 * Do not edit by hand — re-run the script after SVG changes.
 */
import type { DynamicPersonaId } from "@/lib/agent/persona/types";

export const PERSONA_IMAGE_INTRINSIC = { width: 256, height: 256 } as const;

export const PERSONA_IMAGE_BLUR: Record<DynamicPersonaId, string> = {
  "warm_instructor": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4WAoAAAAQAAAACwAACwAAQUxQSFEAAAABcFzbttIc3FqAOV1AKU4pVpDFM85KKV4BDi1ExAQAKK4rs6iXv77/5hogX/vFswxZv5pAu1bDc+0B7VoD0VoA1mvpZQL+f/bzmDvV/V7a7AUAVlA4ICwAAADQAQCdASoMAAwABoCQJbACdAEO/09QAAD+rj1eKCiANXBGDMPTe+xQc1AAAA==",
  "strict_coach": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4WAoAAAAQAAAACwAACwAAQUxQSD8AAAABYBTbdpO/TZz00IQwSKj+YAsSoiQW6KQ7iIgJgJxY1bVCjsY8z/OY2lof52Jpl86zuzarO6yjtYD289wTiAUAVlA4IDoAAACwAQCdASoMAAwABoCQJbACdGaAAF0AAK5jqA4i6ATETnx1b+TW0GhPN4WmQLZSMSsM5zApJtUfwAAA",
  "energetic_rapper": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4WAoAAAAQAAAACwAACwAAQUxQSEUAAAABYBMAQBM4NcM8qUMDarjS7FcvT4tsW+zBJkFETACQR4gHw2lLIcPp9uc5+oCqH2ZNkZu6CWWN1GBToKUawMRZlmWYZSAAVlA4IC4AAABwAQCdASoMAAwABoCQJbACw7AAAAD64B8V4oOTmhAsP9oj5rw+R9Sq80bYAAAA",
  "zen_guide": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4WAoAAAAQAAAACwAACwAAQUxQSFMAAAABd6CmkRQ4yh4qMEH1dkREmBMUHLyUYFNt247n+xfj7aGCAEarTRSTClqYzCYxuEt8b4iI/k+AfDvXKL0wyX544gZQ927wlq7YB1fQDaNkxxzkAwBWUDggLgAAAFABAJ0BKgwADAAGgJAlsAAEAAAA/tmBfOFKIn3PcyKL/4kTHLpCtzzUpzVIAAA=",
  "curious_explorer": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4WAoAAAAQAAAACwAACwAAQUxQSFEAAAABcNPa2ttc/ZPnwqHbUOrcCwDLOH48ljFYwZEQSOb6FwoRMQEoHfQikEKzPt7v+6zY38oN8F6qpwvNW1tBp2sh16XAqToA/Nvf5f8hSikLgS0AVlA4IEAAAACwAQCdASoMAAwABoCQJbACdDiAAcmAAP7nWAX1lsMdVt26iACZL1/sKpassxJv6dKEYDBVpYjVf9sN43hOAAAA",
};
